### PR TITLE
Ptrdist/yacr2: Checked Strings

### PR DESCRIPTION
**Pull request by lenary**
The only unchecked code remaining is in two `fscanf`s.

### CODE REVIEW

**Review by dtarditi — APPROVED** [review]
Looks good. 

I do wonder about the fine-grained intermixing of checked and unchecked blocks that is occurring here with the macro for printf.   It isn't very clear in the code that printf is unchecked.

**Comment by lenary** [comment]
Let's talk after the skype meeting about fine-grained mixing.

**Comment by lenary** [comment]
I'm going to merge this, I think it's ok, as long as we track it correctly.

**Comment by dtarditi** [comment]
Yes, that's good with me.

**Pull request merged**
