### PR TITLE
Removes Checked Headers, Instead Includes Headers from Spec Repository

### PR DESCRIPTION
**Pull request by lenary**
This adds a `CHECKEDC_SPEC_DIR` variable to point to where we've checked out Microsoft/checkedc

It will then add the `include` dir in that repository to the include path, so that we can use the checked c headers there. We also remove the `include` dir and its contents from this repository to avoid confusion. We didn't change the Makefiles before, so I'm not changing them now. The previous change to the CMake configuration by us was this: 5c13ec2d7611605e17f35c863a11469784fb95fb

This removes the copy of the headers we have in this repository, because syncing changes is bound to mean we lose changes between both repositories.

This is the diff to my benchmarking scripts that was needed: https://github.com/lenary/checkedc-travis-builder/commit/b5432c68131004d14d7cf525d8d9eb7edcc59f9a

Tested:
- On My Mac
- In the Benchmarking system, using that change to the scripts above.

### CODE REVIEW

**Comment by lenary** [comment]
I'm wrong, it hasn't been tested in the benchmarking system. I set off another run, and there's a failing with `strncmp`. I've just put in a pull request for that. The run passes with that change.

**Review by dtarditi — APPROVED** [review]
Overall, this looks good.  Thank you for doing this.

I did pull down your branch and test it to see of the old makefile-based approach broke.  It did because there are not extra header files for it to find automatically.

However, I did find a way to tell the makefile-based LNT testing to pick up the extra header files.  You can set the ExtraHeaders environment variable used by the makefile.   You can do this by adding to the LNT command line `--make-param=ExtraHeaders={path to the Checked C include directory}`.  Could you update the documentation in the docs directory to describe this?

I've already committed a change to the existing automation (which use the makefiles) to do this.   It passed local testing, so it should work.

**Comment by dtarditi** [comment]
I'm going to commit this now - we can update the documentation later.

**Comment by lenary** [comment]
Oh I can add the Makefile changes too. I should do that.

**Comment by dtarditi** [comment]
Yes, it turns out that I misunderstood the ExtraHeaders makefile variable.  It doesn't do anything when compiling C programs.  I think the makefiles need to be modified directly to add an extra variable.

**Comment by dtarditi** [comment]
The fact that ExtraHeaders does not do anything for compiling C programs caused the automation for LNT to break.   I tried going ahead and enabling automation to run LNT using cmake in the checked-clang repo.   That broke in new ways - it apparently requires that the LLVM Gold plugin be built.  

I've reverted the change to the LLVM test suite and the changes to automation too.   Yes, it would be good to update the LNT makefile-based system too.

**Comment by dtarditi** [comment]
It is a little worrisome that we are relying on include directories only.   Someone could change a header file in the include directory.   The build system wouldn't notice this change because there is no explicit dependency on the header file.   It would not recompile existing applications, so we would not test the change.  We already have this problem, so this change doesn't introduce the problem.

**Comment by lenary** [comment]
Ok, I will add the changes to the Makefile system.

Because the makefile system uses `${CC} -MM` to generate dependency information for Make, and this information does include the Checked C headers if we add `-I${CHECKEDC_SPEC_DIR}/include` to the C args, that should mean we pick up any changes to the checked c headers if any of them change.

I think LNT should be cleaning out the test sandbox directory for every run, forcing recompilation anyway, or else it can't be correctly recording new compile times for the programs. That said, I don't understand the Makefile system entirely, and it wouldn't surprise me if it wasn't blowing away the sandbox directory because it didn't need to record timing statistics.

**Comment by dtarditi** [comment]
Thanks for pointing out how header file dependences are computed. 

In general, we will face the  problem that people will want the Checked C version of the header files.   I am thinking about modifying clang to copy them into its system header files.  Yes, that is kind of hacky, but otherwise people have to make their own separate copy. 

From briefly skimming the GNU make documentation, it looks like we'd have to use the -M option to keep the dependencies right.   Perhaps not, though.  I don't understand how LNT is picking up changes in the toolchain.

**Comment by lenary** [comment]
I also just discovered that `${ExtraHeaders}` in the make system does nothing to the include paths, which probably explains the breakage. Opening a new pull request which includes the changes that make this actually work.

**Pull request merged**
