### PR TITLE
Modifies the Olden/perimeter benchmark for Checked C

### LINKED ISSUE #18: CheckedC convert Olden/perimeter Benchmark

### PR DESCRIPTION
**Pull request by lenary**
Closes #18 

Checked-c-convert converted zero of the pointers in this benchmark.

Everything in the conversion should be straightforward, given this is basically all just using `ptr<T>` and not using `array_ptr<T>`

### CODE REVIEW

**Review by dtarditi — COMMENTED** [review]
Looks good.  I think the malloc in maketree.c should be a calloc to ensure that the pointers in QuadTree are initialized properly.

**Comment by lenary** [comment]
With the comment about calloc, should I be going through and changing all `malloc` calls to `calloc`?

**Comment by lenary** [comment]
(i.e, all `malloc` calls in our converted benchmarks, not just perimeter)

**Comment by dtarditi** [comment]
malloc's of data that contain checked pointers should be replaced with calloc or something that zeros the pointers.   This is something that I should have pointed out earlier.   I realized last week that I was overlooking it.

**Review by dtarditi — APPROVED** [review]

**Pull request merged**
